# Check that syntax is correct

name: imgCIFSyntaxandConformanceCheck

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
            - 'Laboratory/*.cif'
            - 'Beamlines/*.cif'

  pull_request:
    paths:
            - 'Laboratory/*.cif'
            - 'Beamlines/*.cif'

  workflow_dispatch:   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  syntax:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: checkout
          uses: actions/checkout@v2
          
      # Check syntax of all CIF files
        - name: check_lab_syntax
          uses: COMCIFS/cif_syntax_check_action@master
          with:
            check-directory: Laboratory
          id: cif_lab_check
        - name: check_bl_syntax
          uses: COMCIFS/cif_syntax_check_action@master
          with:
            check-directory: Beamlines
          id: cif_bl_check
